@startuml

rectangle "Demo communications" { 

    rectangle Micro-Ros {
        (Actuator node) 
        (Display node)
        (Actitude sensor node) 
    }

    rectangle Ros2 {
        (Control core node) 
    }


    
    (Actitude sensor node) ..> (Display node): Altitude [m]
    (Actitude sensor node) ..> (Control core node): Altitude [m]
    (Control core node) ..> (Actuator node): Engine power inc [Watt]
    (Control core node) ..> (Display node): Status message
    (Actuator node) .> (Display node): Engine power [Watt]
    }
@enduml