@startuml
    box "MicroROS" #LightBlue
	    participant position_sensor
	    participant actuator
	    participant display
    end box
        
    box "Ros2" #SeaShell
	    participant external_node
    end box
    
    position_sensor ->  actuator: Altura (1200 m)
    position_sensor ->  actuator: Altura (1150 m)
    position_sensor ->  actuator: Altura (1075 m)
    ...
    position_sensor ->  actuator: Altura (920 m)
    actuator -> display : warning!!
    actuator -> external_node: warning!!
    
    position_sensor ->  actuator: Altura (499 m)
    actuator -> display : Failure!!
    actuator -> external_node: Failure!!
    external_node -> actuator: +10 W

    position_sensor ->  actuator: Altura (999 m)
    actuator -> display : warning!!
    actuator -> external_node: warning!!

    ...
    position_sensor ->  actuator: Altura (1001 m)
    position_sensor ->  actuator: Altura (1010 m)
    position_sensor ->  actuator: Altura (1500 m)
    ...    
@enduml