@startuml
    box "MicroROS" #LightBlue
	    participant actuator
	    participant display
        participant Altitude_sensor
    end box
        
    box "Ros2" #SeaShell
	    participant control_core
    end box
    
    actuator -> display: [uint32] Engine power: 100 Watt
    Altitude_sensor ->  control_core: [float64] Altitude: 1200 m
    Altitude_sensor ->  display: [float64] Altitude: 1200 m
    Altitude_sensor ->  control_core: [float64] Altitude: 1150 m
    Altitude_sensor ->  display: [float64] Altitude: 1150 m
    Altitude_sensor ->  control_core: [float64] Altitude: 1075 m
    Altitude_sensor ->  display: [float64] Altitude: 1075 m
    ...
    Altitude_sensor ->  control_core: [float64] Altitude: 920 m
    Altitude_sensor ->  display: [float64] Altitude: 920 m
    control_core -> display : [string] Altitude low!!
    control_core -> actuator: [int32] Increase engine power: +5 Watt
    actuator -> display: [uint32] Engine power: 105 Watt
    
    Altitude_sensor ->  control_core: [float64] Altitude: 499 m
    Altitude_sensor ->  display: [float64] Altitude: 499 m
    control_core -> display : [string] Altitude too low!!
    control_core -> actuator: [int32] Increase engine power: +10 Watt
    actuator -> display: [uint32] Engine power: 115 Watt

    Altitude_sensor ->  control_core: [float64] Altitude: 999 m
    control_core -> display : [string] warning!!
    control_core -> actuator: [int32] Increase engine power: +5 Watt
    actuator -> display: [uint32] Engine power: 120 Watt

    ...
    Altitude_sensor ->  control_core: [float64] Altitude: 1001 m
    Altitude_sensor ->  control_core: [float64] Altitude: 1010 m
    Altitude_sensor ->  control_core: [float64] Altitude: 1500 m
    ...    
@enduml