@startuml
    box "MicroROS" #LightBlue
	    participant position_sensor
	    participant actuator
	    participant display
    end box
        
    box "Ros2" #SeaShell
	    participant external_node
    end box
    
    position_sensor ->  actuator: Altitude: 1200 m
    position_sensor ->  actuator: Altitude: 1150 m
    position_sensor ->  actuator: Altitude: 1075 m
    ...
    position_sensor ->  actuator: Altitude: 920 m
    actuator -> display : warning!!
    actuator -> external_node: warning!!
    external_node -> actuator: Engine power: +5 Watt
    
    position_sensor ->  actuator: Altitude: 499 m
    actuator -> display : Failure!!
    actuator -> external_node: Failure!!
    external_node -> actuator: Engine power: +10 Watt

    position_sensor ->  actuator: Altitude: 999 m
    actuator -> display : warning!!
    actuator -> external_node: warning!!
    external_node -> actuator: Engine power: +5 Watt

    ...
    position_sensor ->  actuator: Altitude: 1001 m
    position_sensor ->  actuator: Altitude: 1010 m
    position_sensor ->  actuator: Altitude: 1500 m
    ...    
@enduml